clc;clear;
%读入图像
I1=imread('goose.jpg');
subplot(2,3,1);imshow(I1);title('原始图像');
%转成灰度图像
[width,height,z]=size(I1);
if(z>1)
    I=rgb2gray(I1);
end
subplot(2,3,2);imshow(I);title('灰度图像');
%加入高斯噪声
av=0;
std=0.1;
u1=rand(width,height);
u2=rand(width,height);
x=std*sqrt(-2*log(u1)).*cos(2*pi*u2)+av;
G1=double(I)/255+x;
G=uint8(255*G1);
subplot(2,3,3);imshow(G);title('加入高斯噪声之后的图像');
%中值滤波
x1=medfilt2(G,[5,5]);
subplot(2,3,4);imshow(x1);title('中值滤波后的图像');
%均值滤波
x2=filter2(fspecial('average',3),G)/255;
subplot(2,3,5);imshow(x2);title('均值滤波后的图像');
%高斯滤波
x3=imfilter(G,fspecial('gaussian',[3,3],1),'replicate');
subplot(2,3,6);imshow(x3);title('高斯滤波后的图像');